version: '3.9'
services:
  puppy:
    image: $CONTAINER_REGISTRY/puppy/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/puppy/internal/image.binary"
    env_file: ../../applications/puppy/.env.ci
    depends_on:
      - temporal
    ports:
      - 3060:8000
      - 3070:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - puppy
