import JSResource from './utilities/JSResource';
import RelayEnvironment from './RelayEnvironment';
import { graphql, loadEntryPoint } from 'react-relay/hooks';
import { TokenQuery } from './queries/token';

const environmentProvider = { getEnvironment: () => RelayEnvironment };

const TokenRoot = JSResource('TokenRoot', () =>
  import('./components/TokenRoot'),
);

const routes = [
  {
    prepare: function() {},
    component: JSResource('Root', () => import('./Root')),
    routes: [
      {
        path: '/join',
        exact: true,
        component: JSResource('JoinRoot', () =>
          import('./components/JoinRoot'),
        ),
        prepare: function() {},
      },
      {
        path: '/token/:id',
        component: TokenRoot,
        prepare: params => {
          return loadEntryPoint(
            environmentProvider,
            {
              root: TokenRoot,
              getPreloadProps(params) {
                return {
                  // we may want to pass some extra props to the react component.
                  extraProps: {},
                  // nested entrypoints will be defined here
                  entryPoints: {},
                  // queries will be defined here.
                  queries: {
                    tokenQuery: {
                      // the AST generated by relay-compiler
                      parameters: TokenQuery,
                      // the variables the query may need.
                      variables: { cookie: params.cookie },
                    },
                  },
                };
              },
            },
            { cookie: params.id },
          );
        },
      },
    ],
  },
];

export default routes;
