version: '2.2'
services:
  carrier:
    image: $CONTAINER_REGISTRY/carrier/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/carrier/internal/image.binary"
    env_file: ../../applications/carrier/.env.ci
    depends_on:
      - temporal
      - redis
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    ports:
      - 5030:8080
    restart: "on-failure:20"
    cpus: 0.1

  run:
    depends_on:
      - carrier
