version: '3.9'
services:
  carrier:
    image: $CONTAINER_REGISTRY/carrier/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/carrier/internal/image.binary"
    env_file: ../../applications/carrier/.env.ci
    depends_on:
      - temporal
      - redis
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    ports:
      - 5030:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - carrier
