services_steps:
  build:
    targets:
      - //applications/carrier/internal:internal

  unit_test:
    coverage:
      - name: carrier.unit
        paths:
          - ./applications/carrier/**/coverage.dat
    targets:
      - //applications/carrier/internal/app/...
      - //applications/carrier/internal/domain/...
      - //applications/carrier/internal/ports/...

  push_image:
    targets:
      - //applications/carrier/internal:publish

  integration_test:
    setup:
      dockerfile:
        - ./applications/carrier/docker-compose.ci.yaml
    coverage:
      - name: carrier.integration
        paths:
          - ./applications/carrier/internal/adapters/**/coverage.dat
      - name: carrier.component
        paths:
          - ./applications/carrier/internal/service/**/coverage.dat
    targets:
      - //applications/carrier/internal/adapters/...
      - //applications/carrier/internal/service/...

  e2e_test:
    setup:
      dockerfile:
        - ./applications/carrier/docker-compose.ci.yaml
