steps:
  build:
    targets:
      - //applications/carrier/internal:image

  unit_test:
    coverage:
      - name: carrier.unit
        paths:
          - ./applications/carrier/**/coverage.dat
    targets:
      - //applications/carrier/internal/app/...
      - //applications/carrier/internal/domain/...
      - //applications/carrier/internal/ports/...

  integration_test:
    coverage:
      - name: carrier.integration
        paths:
          - ./applications/carrier/internal/adapters/**/coverage.dat
      - name: carrier.component
        paths:
          - ./applications/carrier/internal/service/**/coverage.dat
    targets:
      - //applications/carrier/internal/adapters/...
      - //applications/carrier/internal/service/...

  push_image:
    targets:
      - //applications/carrier/internal:publish

  e2e_test:
    setup:
      dockerfile:
        - ./applications/carrier/docker-compose.ci.e2e.yaml

  publish_image:
    copy:
      - from_repo: carrier/dev
        to_repo: carrier
