apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-node
  labels:
    app: example-node
spec:
  selector:
    matchLabels:
      app: example-node
  template:
    metadata:
      labels:
        app: example-node
    spec:
      containers:
        - name: example-node
          image: example-node-image
          ports:
            - containerPort: 9000