kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: example-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api/graphql
            backend:
              serviceName: hades
              servicePort: 8000
          - path: /
            backend:
              serviceName: medusa
              servicePort: 8000