apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-cluster-member
---
# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-cluster-member
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simple-cluster-member
subjects:
  - kind: ServiceAccount
    name: simple-cluster-member
    namespace: default
---