apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mount-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mount
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  capacity:
    storage: 2Gi
  hostPath:
    path: "{{ .Values.mountDirectory }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "default-service.fullname" . }}
  labels:
  {{- include "default-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "default-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "default-service.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: data-mount-storage
          persistentVolumeClaim:
            claimName: data-mount-claim
      containers:
        - name: {{ include "default-service.fullname" . }}
          image: "{{ .Values.image.repository }}"
          volumeMounts:
            - mountPath: /var/data
              name: data-mount-storage
          ports:
            {{- if .Values.grpc }}
            - name: grpc
              containerPort: 8080
              protocol: TCP
            {{- end }}
            {{- if .Values.http }}
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- end  }}
          {{- if or $.Values.env $.Values.envSecrets }}
          env:
            - name: TEMPORAL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secret := $.Values.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret }}
                  key: {{ $key | quote }}
  {{- end }}
  {{- end }}
