codecov:
  require_ci_to_pass: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes
  javascript:
    enable_partials: yes

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: no

coverage:
  status:
    # no patch status for now
    patch: off
    project:
      default:
        informational: true
        paths:
          - "applications"
          - "libraries"
      medusa:
        informational: true
        paths:
          - "applications/medusa"
      eva:
        informational: true
        paths:
          - "applications/eva"
      buffer:
        informational: true
        paths:
          - "applications/buffer"
      sting:
        informational: true
        paths:
          - "applications/sting"
      library:
        informational: true
        paths:
          - "libraries"
ignore:
  - "**/generated.go"
  - "**/*.pb.go"
  - "**/federation.go"

# fix path for bazel-generated coverage files && cypress
fixes:
  - "/workdir/personal/overdoll/::"
  - "overdoll/applications/::applications/"