version = 1

test_patterns = [
    "**/*.spec.js",
    "**/*/*.spec.js",
    "**/__tests__/**",
    "tests/*_test.go",
    "**/*_test.go",
]

exclude_patterns = [
    "**/__generated__/**",
    "**/__docs__/**",
    "**/*/*.stories.js",
    ".buildkite/**",
    ".github/**",
    ".patches/**",
    "applications/medusa/.storybook/**",
    "applications/medusa/src/types/external/**"
]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = "overdoll"
dependencies_vendored = true

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["react"]
environment = ["jest", "cypress", "nodejs", "browser"]
module_system = "es-modules"
dialect = "flow"
style_guide = "standard"

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true
