version = 1

test_patterns = [
    "**/*.ispec.js",
    "**/*.uspec.js",
    "**/*.spec.js",
    "**/*/*.spec.js",
    "**/*/*.ispec.js",
    "**/*/*.uspec.js",
    "**/__tests__/**"
]

exclude_patterns = [
    "**/__generated__/**",
    ".buildkite/**",
    ".github/**",
    ".patches/**",
    "applications/medusa/.storybook/**",
    "applications/medusa/cypress/**"
]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = "overdoll"
dependencies_vendored = false
build_tags = ["darwin"]
cgo_enabled = false

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["react"]
module_system = "es-modules"
dialect = "flow"
style_guide = "airbnb"

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true
