apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: orca
    app.kubernetes.io/managed-by: tilt
    app.kubernetes.io/name: orca
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: default-service-0.1.0
  name: orca
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: orca
    app.kubernetes.io/name: orca
  sessionAffinity: None
  type: ClusterIP