// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	proto "overdoll/libraries/media/proto"
)

// MockMediaCallbackClient is an autogenerated mock type for the MediaCallbackClient type
type MockMediaCallbackClient struct {
	mock.Mock
}

// UpdateMedia provides a mock function with given fields: ctx, in, opts
func (_m *MockMediaCallbackClient) UpdateMedia(ctx context.Context, in *proto.UpdateMediaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *emptypb.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateMediaRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateMediaRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockMediaCallbackClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMediaCallbackClient creates a new instance of MockMediaCallbackClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMediaCallbackClient(t mockConstructorTestingTNewMockMediaCallbackClient) *MockMediaCallbackClient {
	mock := &MockMediaCallbackClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
