// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "overdoll/libraries/resource/proto"
)

// MockResourceCallbackClient is an autogenerated mock type for the ResourceCallbackClient type
type MockResourceCallbackClient struct {
	mock.Mock
}

// UpdateResources provides a mock function with given fields: ctx, in, opts
func (_m *MockResourceCallbackClient) UpdateResources(ctx context.Context, in *proto.UpdateResourcesRequest, opts ...grpc.CallOption) (*proto.UpdateResourcesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.UpdateResourcesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateResourcesRequest, ...grpc.CallOption) *proto.UpdateResourcesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UpdateResourcesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateResourcesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockResourceCallbackClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockResourceCallbackClient creates a new instance of MockResourceCallbackClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockResourceCallbackClient(t mockConstructorTestingTNewMockResourceCallbackClient) *MockResourceCallbackClient {
	mock := &MockResourceCallbackClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
