{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "default-service.fullname" . }}
  labels:
    {{- include "default-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.http }}
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.grpc }}
    - port: 8080
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    {{- include "default-service.selectorLabels" . | nindent 4 }}
{{- end }}