version: '3.9'
services:
  eva:
    image: $CONTAINER_REGISTRY/parley/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/parley/image.binary db migrate keyspace && /app/applications/parley/image.binary db seed && /app/applications/parley/image.binary"
    env_file: ../../applications/parley/.env.ci
    depends_on:
      - temporal
    ports:
      - 3020:8000
      - 3030:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - sting