version: '2.2'
services:
  parley:
    image: $CONTAINER_REGISTRY/parley/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/parley/internal/image.binary db migrate keyspace && /app/applications/parley/internal/image.binary db seed && /app/applications/parley/internal/image.binary"
    env_file: ../../applications/parley/.env.ci
    depends_on:
      - temporal
    ports:
      - 3060:8000
      - 3070:8080
    restart: "on-failure:20"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.1

  run:
    depends_on:
      - parley
