steps:
  build:
    targets:
      - //applications/parley/internal:internal

  unit_test:
    coverage:
      - name: parley.unit
        paths:
          - ./applications/parley/**/coverage.dat
    targets:
      - //applications/parley/internal/app/...
      - //applications/parley/internal/domain/...
      - //applications/parley/internal/ports/...

  integration_test:
    pre_hook:
      - //applications/parley/internal:internal -- db migrate keyspace
      - //applications/parley/internal:internal -- db seed
    coverage:
      - name: parley.integration
        paths:
          - ./applications/parley/internal/adapters/**/coverage.dat
      - name: parley.component
        paths:
          - ./applications/parley/internal/service/**/coverage.dat
    targets:
      - //applications/parley/internal/adapters/...
      - //applications/parley/internal/service/...

  push_image:
    targets:
      - //applications/parley/internal:publish

  e2e_test:
    setup:
      dockerfile:
        - ./applications/parley/docker-compose.ci.yaml
        - ./applications/stella/docker-compose.ci.e2e.yaml
    network_dependencies:
      - host: parley
        port: 8000
        priority: 0

  publish_image:
    copy:
      - from_repo: parley/dev
        to_repo: parley
