steps:
  build:
    targets:
      - //applications/parley:parley

  push_image:
    targets:
      - //applications/parley:publish-testing

  integration_test:
    setup:
      dockerfile:
        - ./applications/parley/docker-compose.ci.yaml
    network_dependencies:
      - host: parley
        port: 8000

  e2e_test:
    setup:
      dockerfile:
        - ./applications/parley/docker-compose.ci.yaml
    network_dependencies:
      - host: parley
        port: 8000
        priority: 0

  publish_image:
    targets:
      - //applications/parley:publish