// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type AuditUser struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type ModeratePost struct {
	AuditLog   *PendingPostAuditLog `json:"auditLog"`
	Validation *Validation          `json:"validation"`
}

type ModeratePostInput struct {
	PendingPostID     string  `json:"pendingPostId"`
	RejectionReasonID *string `json:"rejectionReasonId"`
	Notes             string  `json:"notes"`
}

type PendingPostAuditLog struct {
	ID           string     `json:"id"`
	PostID       string     `json:"postId"`
	Contributor  *AuditUser `json:"contributor"`
	Moderator    *AuditUser `json:"moderator"`
	InfractionID *string    `json:"infractionId"`
	Status       string     `json:"status"`
	Reason       string     `json:"reason"`
	Notes        string     `json:"notes"`
	Reverted     bool       `json:"reverted"`
}

type PendingPostAuditLogInput struct {
	ModeratorID string `json:"moderatorId"`
}

type PendingPostRejectionReason struct {
	ID         string `json:"id"`
	Reason     string `json:"reason"`
	Infraction bool   `json:"infraction"`
}

type RevertPostInput struct {
	AuditLogID string `json:"auditLogId"`
}

type User struct {
	ID                string                    `json:"id"`
	InfractionHistory []*UsersInfractionHistory `json:"infractionHistory"`
}

func (User) IsEntity() {}

type UsersInfractionHistory struct {
	ID     string `json:"id"`
	Reason string `json:"reason"`
}

type Validation struct {
	Code string `json:"code"`
}
