// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type PendingPostRejectionReason struct {
	ID         string `json:"id"`
	Reason     string `json:"reason"`
	Infraction bool   `json:"infraction"`
}

type Workaround3 struct {
	ID *int `json:"id"`
}

func (Workaround3) IsEntity() {}
