// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthenticationCookie struct {
	Cookie     string `json:"cookie"`
	Email      string `json:"email"`
	Redeemed   bool   `json:"redeemed"`
	Expiration string `json:"expiration"`
}
