services_steps:
  push_image:
    targets:
      - //applications/orca:publish

  e2e_test:
    setup:
      dockerfile:
        - ./applications/orca/docker-compose.e2e.yaml
    network_dependencies:
      - host: orca
        port: 8000
        priority: 0
