// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type Artist struct {
	ID       string `json:"id"`
	Avatar   string `json:"avatar"`
	Username string `json:"username"`
}

type Category struct {
	ID        string `json:"id"`
	Thumbnail string `json:"thumbnail"`
	Title     string `json:"title"`
}

type Character struct {
	ID        string `json:"id"`
	Thumbnail string `json:"thumbnail"`
	Name      string `json:"name"`
	Media     *Media `json:"media"`
}

type CharacterRequest struct {
	Name  string `json:"name"`
	Media string `json:"media"`
}

type Media struct {
	ID        string `json:"id"`
	Thumbnail string `json:"thumbnail"`
	Title     string `json:"title"`
}

type PostInput struct {
	Content           []string            `json:"content"`
	Categories        []string            `json:"categories"`
	Characters        []string            `json:"characters"`
	MediaRequests     []string            `json:"mediaRequests"`
	CharacterRequests []*CharacterRequest `json:"characterRequests"`
	ArtistID          *string             `json:"artistId"`
	ArtistUsername    string              `json:"artistUsername"`
}

type PostResponse struct {
	Review     bool        `json:"review"`
	Validation *Validation `json:"validation"`
}

type PostUpdateResponse struct {
	Validation *Validation `json:"validation"`
}

type SearchInput struct {
	Search string `json:"search"`
}

type Validation struct {
	Code string `json:"code"`
}

type Workaround2 struct {
	ID *int `json:"id"`
}

func (Workaround2) IsEntity() {}
