services:
  sting-init:
    image: $DOCKER_REGISTRY/sting-dev:$CONTAINER_TAG
    command: >
      ./sting_ db migrate
      && ./sting_ db seed
      && ./sting_ index all
    env_file:
      - .env.ci
    depends_on:
      - elasticsearch
      - temporal

  sting-http:
    image: $DOCKER_REGISTRY/sting-dev:$CONTAINER_TAG
    command: ./sting_ http
    ports:
      - "127.0.0.1:3010:$PORT"
    env_file:
      - .env.ci
    depends_on:
      - sting-init

  sting-worker:
    image: $DOCKER_REGISTRY/sting-dev:$CONTAINER_TAG
    command: >
      ./sting_ worker
    ports:
      - "127.0.0.1:3010:$PORT"
    env_file:
      - .env.ci
    depends_on:
      - sting-init