build:
  targets:
    - //applications/sting:sting

unit_test:
  targets:
    - //applications/sting/src/app/...
    - //applications/sting/src/domain/...
    - //applications/sting/src/ports/...

integration_test:
  setup:
    target: //applications/sting:publish-testing
    dockerfile: ./applications/sting/.ci/docker-compose.yaml
  targets:
    - //applications/sting/src/adapters/...
    - //applications/sting/src/service/...