steps:
  build:
    targets:
      - //applications/sting:sting
    push:
      - //applications/sting:publish-testing

  unit_test:
    targets:
      - //applications/sting/src/app/...
      - //applications/sting/src/domain/...
      - //applications/sting/src/ports/...

  integration_test:
    setup:
      dockerfile:
        - ./applications/sting/.ci/docker-compose.yaml
    targets:
      - //applications/sting/src/adapters/...
      - //applications/sting/src/service/...

  e2e_test:
    setup:
      dockerfile:
        - ./applications/sting/.ci/docker-compose.yaml