apiVersion: apps/v1
kind: Deployment
metadata:
  name: eva
  labels:
    app: eva
spec:
  selector:
    matchLabels:
      app: eva
  template:
    metadata:
      labels:
        app: eva
    spec:
      containers:
        - name: eva
          image: eva-image
          ports:
            - containerPort: 8000