const STEPS = {
  REVIEW: 'REVIEW',
  ARRANGE: 'ARRANGE',
  FINISH: 'FINISH',
  TAG: 'TAG',
};

const EVENTS = {
  THUMBNAILS: 'THUMBNAILS',
  URLS: 'URLS',
  FILES: 'FILES',
  STEP: 'STEP',
  PROGRESS: 'PROGRESS',
  TAG_CHARACTERS: 'TAG_CHARACTERS',
  TAG_ARTIST: 'TAG_ARTIST',
  TAG_CATEGORIES: 'TAG_CATEGORIES',
  SUBMIT: 'SUBMIT',
  ALL: 'ALL',
};

export { STEPS, EVENTS };
