version: '3.9'
services:
  traefik:
    image: traefik:v2.1
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - 8000:80
      - 4343:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  run:
    working_dir: /workdir
    image: "cypress/included:7.2.0"
    entrypoint: ""
    privileged: true
    environment:
      - HOME=/var/lib/buildkite-agent
    volumes:
      - $BUILDKITE_BUILD_CHECKOUT_PATH:/workdir
      - /var/lib/buildkite-agent:/var/lib/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent

volumes:
  minio-data:
    driver: local