version: '3.9'
services:
  run:
    working_dir: /workdir
    image: "gcr.io/bazel-public/ubuntu1804-java11@sha256:54af0180aaa595b2a10edce51e3ec71923b2e21c3964ffc0938c6f599f0b35e3"
    user: 2000:2000
    privileged: true
    group_add:
      - 1001
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /opt:/opt:ro
      - /var/lib/buildkite-agent:/var/lib/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
      - $BUILDKITE_BUILD_CHECKOUT_PATH:/workdir
