version: '3.9'
services:
  run:
    image: "gcr.io/bazel-public/ubuntu1804-java11"
    working_dir: /workdir
    user: 2000:2000
    privileged: true
    group_add:
      - 1001
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /opt:/opt:ro
      - /var/lib/buildkite-agent:/var/lib/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
      - $BUILDKITE_BUILD_CHECKOUT_PATH:/workdir