version: '3.9'
services:
  run:
    working_dir: /workdir
    image: "771779017151.dkr.ecr.us-east-1.amazonaws.com/ci@sha256:bce0ac8ff9fc0642f23d70e2e6d97946b6e1dc492e9ea8aeeb3e974581dc05c4"
    user: 2000:2000
    privileged: true
    group_add:
      - 1001
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /opt:/opt:ro
      - /var/lib/buildkite-agent:/var/lib/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
      - $BUILDKITE_BUILD_CHECKOUT_PATH:/workdir
