version: '3.9'
services:
  run:
    working_dir: /workdir
    image: "cypress/included:3.2.0"
    entrypoint: /bin/bash
    user: 2000:2000
    privileged: true
    group_add:
      - 1001
    volumes:
      - $BUILDKITE_BUILD_CHECKOUT_PATH:/workdir
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /opt:/opt:ro
      - /var/lib/buildkite-agent:/var/lib/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent