version: '3.9'
services:
  run:
    working_dir: /workdir
    image: "cypress/included:9.2.0"
    entrypoint: ""
    privileged: true
    environment:
      - HOME=/var/lib/buildkite-agent
    volumes:
      - $BUILDKITE_BUILD_CHECKOUT_PATH:/workdir
      - /var/lib/buildkite-agent:/var/lib/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    depends_on:
      - scylla
      - elasticsearch
      - redis
      - temporal
      - traefik
