version: '3.9'
services:
  redis:
    image: "redis:5.0-alpine3.13"
    ports:
      - 6379:6379

  minio:
    image: minio/minio:RELEASE.2021-05-16T05-32-34Z
    entrypoint: sh
    command: -c 'mkdir -p /export/overdoll-processing && mkdir -p /export/overdoll-post-content && mkdir -p /export/overdoll-uploads && /usr/bin/minio server /export'
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: overdoll123
      MINIO_SECRET_KEY: overdoll123
      MINIO_ROOT_USER: overdollroot
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  traefik:
    image: traefik:v2.1
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - 8000:80
      - 4343:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  run:
    working_dir: /workdir
    image: "cypress/included:7.2.0"
    entrypoint: ""
    privileged: true
    environment:
      - HOME=/var/lib/buildkite-agent
    volumes:
      - $BUILDKITE_BUILD_CHECKOUT_PATH:/workdir
      - /var/lib/buildkite-agent:/var/lib/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent

volumes:
  minio-data:
    driver: local