version: '3.9'
services:

  bazel_remote_cache:
    image: "buchgr/bazel-remote-cache"
    user: 0:0
    environment:
      - BAZEL_REMOTE_S3_AUTH_METHOD=access_key
      - BAZEL_REMOTE_S3_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - BAZEL_REMOTE_S3_SECRET_ACCESS_KEY=${AWS_ACCESS_SECRET}
      - BAZEL_REMOTE_S3_BUCKET=bazel-remote-cache
      - BAZEL_REMOTE_S3_ENDPOINT=s3.us-east-1.amazonaws.com
      - BAZEL_REMOTE_DIR=/data
      - BAZEL_REMOTE_MAX_SIZE=15
    ports:
      - 9090:8080
      - 9092:9092
    volumes:
      - bazel-remote-cache-data:/data

volumes:
  bazel-remote-cache-data:
    driver: local
