// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"overdoll/libraries/graphql/relay"
)

type Account struct {
	ID relay.ID `json:"id"`
}

func (Account) IsEntity() {}

type CCBillPaymentLink struct {
	Link string `json:"link"`
}

type Club struct {
	ID relay.ID `json:"id"`
}

func (Club) IsEntity() {}

// Generate ccbill club supporter payment link.
type GenerateCCBillClubSupporterPaymentLinkInput struct {
	// The chosen club ID.
	ClubID relay.ID `json:"clubId"`
	// Whether or not we want to save the payment details for later.
	SavePaymentDetailsForLater bool `json:"savePaymentDetailsForLater"`
}

// Payload for a new ccbill payment link
type GenerateCCBillClubSupporterPaymentLinkPayload struct {
	// The new payment link
	CcbillPaymentLink *CCBillPaymentLink `json:"ccbillPaymentLink"`
}

type Language struct {
	// BCP47 locale
	Locale string `json:"locale"`
	// Fully qualified name
	Name string `json:"name"`
}

type Translation struct {
	// The language linked to this translation.
	Language *Language `json:"language"`
	// The translation text.
	Text string `json:"text"`
}
