version: '3.9'
services:
  # for e2e tests, we need a worker
  sting-worker:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/sting/internal/image.binary db migrate keyspace && /app/applications/sting/internal/image.binary db seed && /app/applications/sting/internal/image.binary index all && /app/applications/sting/internal/image.binary worker"
    env_file: ../../applications/sting/.env.ci
    depends_on:
      - temporal
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20
    networks:
      web:

  run:
    depends_on:
      - sting-worker
