version: '3.9'
services:
  sting:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    command: ./sting_ db migrate keyspace && ./sting_ db seed && ./sting_ index all && ./sting_
    env_file: ../../applications/sting/.env.ci
    depends_on:
      - elasticsearch
      - temporal
      - scylla
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - sting