version: '3.9'
services:
  sting:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    command: db migrate keyspace && db seed && index all && sting
    env_file: ../../applications/sting/.env.ci
    depends_on:
      - elasticsearch
      - temporal
      - scylla
    ports:
      - 3040:8000
      - 3050:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - sting