version: '3.5'
services:
  sting-init:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    command: >
      ./sting_ db migrate
      && ./sting_ db seed
      && ./sting_ index all
    env_file:
      - .env.ci
    depends_on:
      - elasticsearch
      - temporal

  sting-http:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    command: ./sting_ http
    ports:
      - "127.0.0.1:3010:8000"
    env_file:
      - .env.ci
    depends_on:
      - sting-init

  sting-worker:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    command: >
      ./sting_ worker
    ports:
      - "127.0.0.1:3010:8080"
    env_file:
      - .env.ci
    depends_on:
      - sting-init