version: '2.2'
services:
  sting:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/sting/internal/image.binary db migrate keyspace && /app/applications/sting/internal/image.binary db seed && /app/applications/sting/internal/image.binary"
    env_file: ../../applications/sting/.env.ci
    depends_on:
      - traefik
      - temporal
      - elasticsearch
    ports:
      - 3040:8000
      - 3050:8080
    restart: "on-failure:20"
    cpus: 0.1

  run:
    depends_on:
      - sting
