version: '3.9'
services:
  sting-init:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    command: ./sting_ db migrate --keyspace && ./sting_ db seed && ./sting_ index all
    env_file: ../../applications/sting/.env.ci
    depends_on:
      - elasticsearch
      - temporal
      - scylla
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  sting:
    image: $CONTAINER_REGISTRY/sting/dev:$BUILDKITE_COMMIT
    ports:
      - 3040:8000
      - 3050:8080
    env_file: ../../applications/sting/.env.ci
    depends_on:
      - sting-init
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  run:
    depends_on:
      - sting