steps:
  build:
    targets:
      - //applications/sting/internal:internal

  unit_test:
    coverage:
      - name: sting.unit
        paths:
          - ./applications/sting/**/coverage.dat
    targets:
      - //applications/sting/internal/app/...
      - //applications/sting/internal/domain/...
      - //applications/sting/internal/ports/...

  push_image:
    targets:
      - //applications/sting/internal:publish-testing

  integration_test:
    coverage:
      - name: sting.integration
        paths:
          - ./applications/sting/internal/adapters/**/coverage.dat
      - name: sting.component
        paths:
          - ./applications/sting/internal/service/**/coverage.dat
    targets:
      - //applications/sting/internal/adapters/...
      - //applications/sting/internal/service/...

  e2e_test:
    setup:
      dockerfile:
        - ./applications/sting/docker-compose.ci.e2e.yaml
    network_dependencies:
      - host: sting
        port: 8000
        priority: 0

  publish_image:
    targets:
      - //applications/sting/internal:publish
