version: '3.9'
services:
  ringer:
    image: $CONTAINER_REGISTRY/ringer/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/ringer/internal/image.binary db migrate keyspace && /app/applications/ringer/internal/image.binary db seed && /app/applications/ringer/internal/image.binary"
    env_file: ../../applications/ringer/.env.ci
    depends_on:
      - temporal
      - elasticsearch
    ports:
      - 2532:8000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - ringer
