steps:
  build:
    targets:
      - //applications/ringer/internal:image

  unit_test:
    coverage:
      - name: ringer.unit
        paths:
          - ./applications/ringer/**/coverage.dat
    targets:
      - //applications/ringer/internal/app/...
      - //applications/ringer/internal/domain/...
      - //applications/ringer/internal/ports/...

  integration_test:
    pre_hook:
      - //applications/ringer/internal:internal -- db migrate keyspace
      - //applications/ringer/internal:internal -- cache register
      - //applications/ringer/internal:internal -- db seed
      - //applications/ringer/internal:internal -- cache index
    coverage:
      - name: ringer.integration
        paths:
          - ./applications/ringer/internal/adapters/**/coverage.dat
      - name: ringer.component
        paths:
          - ./applications/ringer/internal/service/**/coverage.dat
    targets:
      - //applications/ringer/internal/adapters/...
      - //applications/ringer/internal/service/...

  push_image:
    targets:
      - //applications/ringer/internal:publish

  e2e_test:
    setup:
      dockerfile:
        - ./applications/ringer/docker-compose.ci.e2e.yaml
    network_dependencies:
      - host: ringer
        port: 8000
        priority: 0

  publish_image:
    copy:
      - from_repo: ringer/dev
        to_repo: ringer
