version: '3.9'
services:
  stella-worker:
    image: $CONTAINER_REGISTRY/stella/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/stella/internal/image.binary db migrate keyspace && /app/applications/stella/internal/image.binary index all && /app/applications/stella/internal/image.binary worker"
    env_file: ../../applications/stella/.env.ci
    depends_on:
      - temporal
      - elasticsearch
      - minio
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - stella-worker
