version: '3.9'
services:
  eva-init:
    image: $CONTAINER_REGISTRY/eva/dev:$BUILDKITE_COMMIT
    command: ./eva_ db migrate --keyspace && ./eva_ db seed
    env_file: ../../applications/eva/.env.ci
    depends_on:
      - elasticsearch
      - scylla

  eva:
    image: $CONTAINER_REGISTRY/eva/dev:$BUILDKITE_COMMIT
    ports:
      - 3020:8000
      - 3030:8080
    env_file: ../../applications/eva/.env.ci
    depends_on:
      - eva-init

  run:
    depends_on:
      - eva