version: '3.9'
services:
  eva:
    image: $CONTAINER_REGISTRY/eva/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/eva/internal/image.binary db migrate keyspace && /app/applications/eva/internal/image.binary db seed && /app/applications/eva/internal/image.binary index all && /app/applications/eva/internal/image.binary"
    env_file: ../../applications/eva/.env.ci
    depends_on:
      - temporal
      - redis
    ports:
      - 3020:8000
      - 3030:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20
    networks:
      web:

  run:
    depends_on:
      - eva
