version: '3.9'
services:
  eva:
    image: $CONTAINER_REGISTRY/eva/dev:$BUILDKITE_COMMIT
    command: ./eva_ db migrate --keyspace && ./eva_ db seed && ./eva_
    ports:
      - 3020:8000
      - 3030:8080
    env_file: ../../applications/eva/.env.ci
    depends_on:
      - elasticsearch
      - scylla
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - eva