version: '2.2'
services:
  eva:
    image: $CONTAINER_REGISTRY/eva/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/eva/internal/image.binary db migrate keyspace && /app/applications/eva/internal/image.binary db seed && /app/applications/eva/internal/image.binary"
    env_file: ../../applications/eva/.env.ci
    depends_on:
      - temporal
      - redis
    ports:
      - 3020:8000
      - 3030:8080
    restart: "on-failure:20"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.2

  run:
    depends_on:
      - eva
