steps:
  build:
    targets:
      - //applications/eva/internal:image

  unit_test:
    coverage:
      - name: eva.unit
        paths:
          - ./applications/eva/**/coverage.dat
    targets:
      - //applications/eva/internal/app/...
      - //applications/eva/internal/domain/...
      - //applications/eva/internal/ports/...

  integration_test:
    pre_hook:
      - //applications/eva/internal:internal -- db migrate keyspace
      - //applications/eva/internal:internal -- db seed
    coverage:
      - name: eva.integration
        paths:
          - ./applications/eva/internal/adapters/**/coverage.dat
      - name: eva.component
        paths:
          - ./applications/eva/internal/service/**/coverage.dat
    targets:
      - //applications/eva/internal/adapters/...
      - //applications/eva/internal/service/...

  push_image:
    targets:
      - //applications/eva/internal:publish

  e2e_test:
    setup:
      dockerfile:
        - ./applications/eva/docker-compose.ci.e2e.yaml
    network_dependencies:
      - host: eva
        port: 8000
        priority: 0

  publish_image:
    copy:
      - from_repo: eva/dev
        to_repo: eva
