steps:
  build:
    targets:
      - //applications/eva/internal:internal

  unit_test:
    coverage:
      - name: eva.unit
        paths:
          - ./applications/eva/**/coverage.dat
    targets:
      - //applications/eva/internal/app/...
      - //applications/eva/internal/domain/...
      - //applications/eva/internal/ports/...

  push_image:
    targets:
      - //applications/eva/internal:publish-testing

  integration_test:
    coverage:
      - name: eva.integration
        paths:
          - ./applications/eva/internal/adapters/**/coverage.dat
      - name: eva.component
        paths:
          - ./applications/eva/internal/service/**/coverage.dat
    targets:
      - //applications/eva/internal/adapters/...
      - //applications/eva/internal/service/...

  e2e_test:
    setup:
      dockerfile:
        - ./applications/eva/docker-compose.ci.yaml
    network_dependencies:
      - host: eva
        port: 8000
        priority: 0

  publish_image:
    targets:
      - //applications/eva/internal:publish
