version: '3.9'
services:
  medusa:
    image: $CONTAINER_REGISTRY/medusa/dev:$BUILDKITE_COMMIT
    env_file: ../../applications/medusa/.env.ci
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20
    depends_on:
      - redis
      - sting
      - eva
      - traefik
    expose: [ 8000 ]
    labels:
      - "traefik.enable=true"
      - "traefik.entrypoints.web.proxyProtocol.trustedIPs=10.0.0.0/16"
      - "traefik.entrypoints.web.forwardedHeaders.trustedIPs=10.0.0.0/16"
      - "traefik.http.routers.medusa.rule=PathPrefix(`/`)"
      - "traefik.http.routers.medusa.entrypoints=web"
      - "traefik.port=8000"

  run:
    volumes:
      - $BUILDKITE_BUILD_CHECKOUT_PATH/applications/medusa/e2e/:/workdir/applications/medusa/coverage/
      - $BUILDKITE_BUILD_CHECKOUT_PATH/cypress/video/:/workdir/applications/medusa/cypress/videos/
      - $BUILDKITE_BUILD_CHECKOUT_PATH/cypress/screenshots/:/workdir/applications/medusa/cypress/screenshots/
    depends_on:
      - medusa
