version: '3.9'
services:
  medusa:
    image: $CONTAINER_REGISTRY/medusa/dev:$BUILDKITE_COMMIT
    env_file: ../../applications/medusa/.env.ci
    depends_on:
      - redis
      - sting
      - eva
    ports:
      - 127.0.0.1:8080:8080

  run:
    volumes:
      - ./artifacts/video/:/workdir/applications/medusa/cypress/videos/
      - ./artifacts/screenshots/:/workdir/applications/medusa/cypress/screenshots/
    depends_on:
      - medusa