version: '3.9'
services:
  medusa:
    image: $CONTAINER_REGISTRY/medusa/dev:$BUILDKITE_COMMIT
    env_file: ../medusa/.env.ci
    depends_on:
      - redis
    ports:
      - 8080:8080

  run:
    depends_on:
      - medusa