version: '3.9'
services:
  medusa:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medusa.rule=PathPrefix(`/`)"
      - "traefik.http.routers.medusa.entrypoints=websecure"
      - "traefik.http.routers.medusa.tls=true"
    depends_on:
      - traefik