version: '3.9'
services:
  medusa:
    # we cant instrument production code, so we run development code instead
    #image: $CONTAINER_REGISTRY/medusa/dev:$BUILDKITE_COMMIT
    image: "gcr.io/bazel-public/ubuntu1804-java11@sha256:54af0180aaa595b2a10edce51e3ec71923b2e21c3964ffc0938c6f599f0b35e3"
    working_dir: /workdir
    user: 2000:2000
    env_file: ../../applications/medusa/.env.ci
    command: npm run service:medusa:e2e
    depends_on:
      - redis
      - sting
      - eva
      - traefik
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /opt:/opt:ro
      - /var/lib/buildkite-agent:/var/lib/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
      - $BUILDKITE_BUILD_CHECKOUT_PATH:/workdir
    ports:
      - 8080:8080
      - 8081:8081
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medusa.rule=PathPrefix(`/`)"
      - "traefik.http.routers.medusa.entrypoints=websecure"
      - "traefik.http.routers.medusa.tls=true"

  run:
    volumes:
      - $BUILDKITE_BUILD_CHECKOUT_PATH/coverage/medusa/:/workdir/applications/medusa/coverage/
      - $BUILDKITE_BUILD_CHECKOUT_PATH/cypress/video/:/workdir/applications/medusa/cypress/videos/
      - $BUILDKITE_BUILD_CHECKOUT_PATH/cypress/screenshots/:/workdir/applications/medusa/cypress/screenshots/
    depends_on:
      - medusa