version: '3.9'
services:
  medusa:
    image: $CONTAINER_REGISTRY/medusa/dev:$BUILDKITE_COMMIT
    env_file: ../../applications/medusa/.env.ci
    depends_on:
      - redis
    ports:
      - 8080:8080

  run:
    image: "cypress/base:12.6.0"
    command: "yarn run test:e2e
    volumes:
      - ./artifacts/video/:/workdir/applications/medusa/cypress/videos/
      - ./artifacts/screenshots/:/workdir/applications/medusa/cypress/screenshots/
    depends_on:
      - medusa