version: '3.9'
services:
  medusa:
    image: $CONTAINER_REGISTRY/medusa/dev:$BUILDKITE_COMMIT
    env_file: ../../applications/medusa/.env.ci
    depends_on:
      - redis
      - sting
      - eva
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    volumes:
      - $BUILDKITE_BUILD_CHECKOUT_PATH/cypress/video/:/workdir/applications/medusa/cypress/videos/
      - $BUILDKITE_BUILD_CHECKOUT_PATH/cypress/screenshots/:/workdir/applications/medusa/cypress/screenshots/
    depends_on:
      - medusa