frontend_steps:
  check:
    workdir: applications/medusa
    commands:
      - ./run_yarn_install.sh
      - yarn run check:tsc
      - yarn run check:eslint
      # needed here to ensure we update to a fresh cache when using a restore key
      - rm ../../v1-cache-medusa-cache_eslint_typescript*

  unit_test:
    workdir: applications/medusa
    coverage:
      - name: medusa.unit
        paths:
          - ./coverage/coverage.dat
    commands:
      - yarn run jest

  build:
    workdir: applications/medusa
    commands:
      - yarn locale:compile
      - yarn build
      # needed here to ensure we update to a fresh cache when using a restore key
      - rm ../../v1-cache-medusa-nextjs*

  push_image:
    workdir: applications/medusa
    build:
      - repo: medusa/dev

steps:
  e2e_test:
    coverage:
      - name: medusa.e2e
        paths:
          - ./applications/medusa/coverage/clover.xml
    setup:
      dockerfile:
        - ./applications/medusa/docker-compose.e2e.yaml
    network_dependencies:
      - host: medusa
        port: 8000
        priority: 1
    artifacts:
      - cypress/**/*
      - cypress/*

  publish_image:
    copy:
      - from_repo: medusa/dev
        to_repo: medusa
