frontend_steps:
  build:
    commands:
      - yarn run locale:compile
      - yarn run check:tsc
      - yarn run check:eslint

  unit_test:
    coverage:
      - name: medusa.unit
        paths:
          - ./applications/medusa/coverage/coverage.dat
    commands:
      - yarn run jest

  push_image:
    commands:
      - docker push -xxxx

  e2e_test:
    commands:
      - yarn run locale:compile
      - yarn run push-all-queries
    coverage:
      - name: medusa.e2e
        paths:
          - ./applications/medusa/coverage/clover.xml
    setup:
      dockerfile:
        - ./applications/medusa/docker-compose.e2e.yaml
    network_dependencies:
      - host: medusa
        port: 8000
        priority: 1
    artifacts:
      - cypress/**/*
      - cypress/*
