steps:
  build:
    commands:
      - bazel build //applications/medusa:packages
      - npm run locale:compile
      - npm run check:tsc
      #- npm run check:eslint
    targets:
      - //applications/medusa:bundle

  unit_test:
    coverage:
      - name: medusa.unit
        paths:
          - ./applications/medusa/unit/coverage.dat
    targets:
      - //applications/medusa:unit

  push_image:
    targets:
      - //applications/medusa:publish-testing

  e2e_test:
    commands:
      # compile localization files
      - npm run locale:compile
    coverage:
      - name: medusa.e2e
        paths:
          - ./applications/medusa/coverage/clover.xml
    setup:
      dockerfile:
        - ./applications/medusa/docker-compose.e2e.yaml
    network_dependencies:
      - host: medusa
        port: 7999
        priority: 1
    artifacts:
      - cypress/**/*
      - cypress/*

  publish_image:
    commands:
      # compile localization files
      - npm run locale:compile
    targets:
      - //applications/medusa:publish
