steps:
  build:
    targets:
      - //applications/medusa:bundle

  unit_test:
    targets:
      - //applications/medusa:unit
      - //applications/medusa:integration

  push_image:
    targets:
      - //applications/medusa:publish-testing

  e2e_test:
    artifacts:
      - './artifacts/**/*'
      - './artifacts/*'
    setup:
      dockerfile:
        - ./applications/medusa/docker-compose.ci.yaml

  publish_image:
    targets:
      - //applications/medusa:publish