frontend_steps:
  check:
    workdir: applications/medusa
    commands:
      - yarn install --frozen-lockfile
      - yarn run check:tsc
      - yarn run check:eslint

  unit_test:
    workdir: applications/medusa
    coverage:
      - name: medusa.unit
        paths:
          - ./coverage/coverage.dat
    commands:
      - yarn run jest

  push_image:
    workdir: applications/medusa
    commands:
      - docker build -t ${CONTAINER_REGISTRY}/medusa/dev/${BUILDKITE_COMMIT} .
      - docker push ${CONTAINER_REGISTRY}/medusa/dev/${BUILDKITE_COMMIT}

steps:
  e2e_test:
    commands:
      - push queries script here!
    coverage:
      - name: medusa.e2e
        paths:
          - ./applications/medusa/coverage/clover.xml
    setup:
      dockerfile:
        - ./applications/medusa/docker-compose.e2e.yaml
    network_dependencies:
      - host: medusa
        port: 8000
        priority: 1
    artifacts:
      - cypress/**/*
      - cypress/*

  publish_image:
    copy:
      - from_repo: medusa/dev
        to_repo: medusa
