// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"fmt"
	"io"
	"overdoll/libraries/graphql/relay"
	"strconv"
	"time"
)

type Account struct {
	// Maximum amount of clubs that you can join as an account.
	ClubMembershipsLimit int `json:"clubMembershipsLimit"`
	// Current count of club memberships. Should be compared against the limit before joining a club.
	ClubMembershipsCount int `json:"clubMembershipsCount"`
	// Represents the clubs that the account has write access to.
	Clubs *ClubConnection `json:"clubs"`
	// Represents the club memberships that the account has.
	ClubMemberships *ClubMemberConnection `json:"clubMemberships"`
	ID              relay.ID              `json:"id"`
}

func (Account) IsEntity() {}

// Add alias slug.
type AddClubSlugAliasInput struct {
	// The club to update
	ID relay.ID `json:"id"`
	// The chosen slug for the club.
	Slug string `json:"slug"`
}

// Payload for a new alt slug
type AddClubSlugAliasPayload struct {
	// The club after update
	Club *Club `json:"club"`
}

// Become a club member.
type BecomeClubMemberInput struct {
	// The chosen club ID.
	ClubID relay.ID `json:"clubId"`
}

// Payload for a new club member
type BecomeClubMemberPayload struct {
	// The membership after creation
	ClubMember *ClubMember `json:"clubMember"`
}

type Club struct {
	// An ID pointing to this club.
	ID relay.ID `json:"id"`
	// An internal reference, uniquely identifying the club.
	Reference string `json:"reference"`
	// A url-friendly ID. Should be used when searching
	Slug string `json:"slug"`
	// An alias list of slugs. These are valid, as in, you can find the club using the slug. However, it should always be replaced by the default slug.
	SlugAliases []*ClubSlugAlias `json:"slugAliases"`
	// Maximum amount of slug aliases that can be created for this club.
	SlugAliasesLimit int `json:"slugAliasesLimit"`
	// A URL pointing to the object's thumbnail.
	Thumbnail *Resource `json:"thumbnail"`
	// A name for this club.
	Name string `json:"name"`
	// The account that owns this club.
	Owner *Account `json:"owner"`
	// The total amount of members in this club.
	MembersCount int `json:"membersCount"`
	// Whether or not the viewer is a member of this club.
	ViewerMember *ClubMember `json:"viewerMember"`
	// Club members.
	Members *ClubMemberConnection `json:"members"`
}

func (Club) IsNode()   {}
func (Club) IsEntity() {}

type ClubConnection struct {
	Edges    []*ClubEdge     `json:"edges"`
	PageInfo *relay.PageInfo `json:"pageInfo"`
}

type ClubEdge struct {
	Cursor string `json:"cursor"`
	Node   *Club  `json:"node"`
}

type ClubMember struct {
	// An ID pointing to this club member.
	ID relay.ID `json:"id"`
	// When the membership was created (when the account originally joined).
	JoinedAt time.Time `json:"joinedAt"`
	// The club that this membership belongs to.
	Club *Club `json:"club"`
	// The account that belongs to this membership.
	Account *Account `json:"account"`
}

func (ClubMember) IsNode()   {}
func (ClubMember) IsEntity() {}

type ClubMemberConnection struct {
	Edges    []*ClubMemberEdge `json:"edges"`
	PageInfo *relay.PageInfo   `json:"pageInfo"`
}

type ClubMemberEdge struct {
	Cursor string      `json:"cursor"`
	Node   *ClubMember `json:"node"`
}

// Ordering options for club members
type ClubMembersOrder struct {
	// The field to order clubs by.
	Field ClubMembersOrderField `json:"field"`
}

// The club slug alias
type ClubSlugAlias struct {
	// The slug alias
	Slug string `json:"slug"`
}

// Ordering options for clubs
type ClubsOrder struct {
	// The field to order clubs by.
	Field ClubsOrderField `json:"field"`
}

// Create club.
type CreateClubInput struct {
	// The chosen slug for the club.
	Slug string `json:"slug"`
	// The chosen name for the club.
	Name string `json:"name"`
}

// Payload for a new club
type CreateClubPayload struct {
	// The club after creation
	Club *Club `json:"club"`
}

// Update alias slug to default.
type PromoteClubSlugAliasToDefaultInput struct {
	// The club to update
	ID relay.ID `json:"id"`
	// The chosen slug for the club.
	Slug string `json:"slug"`
}

// Payload for a new alt slug
type PromoteClubSlugAliasToDefaultPayload struct {
	// The club after update
	Club *Club `json:"club"`
}

// Remove alias slug.
type RemoveClubSlugAliasInput struct {
	// The club to update
	ID relay.ID `json:"id"`
	// The chosen slug for the club.
	Slug string `json:"slug"`
}

// Payload for a new alt slug
type RemoveClubSlugAliasPayload struct {
	// The club after update
	Club *Club `json:"club"`
}

type Resource struct {
	ID relay.ID `json:"id"`
}

func (Resource) IsEntity() {}

// Update club name.
type UpdateClubNameInput struct {
	// The club to update
	ID relay.ID `json:"id"`
	// The chosen name for the club.
	Name string `json:"name"`
}

// Payload for updating the name
type UpdateClubNamePayload struct {
	// The club after update
	Club *Club `json:"club"`
}

// Withdraw club membership.
type WithdrawClubMembershipInput struct {
	// The chosen club ID.
	ClubID relay.ID `json:"clubId"`
}

// Payload for withdrawing club membership
type WithdrawClubMembershipPayload struct {
	// The club membership that was removed
	ClubMemberID relay.ID `json:"clubMemberId"`
}

// Properties by which club member connections can be ordered.
type ClubMembersOrderField string

const (
	// By joined at
	ClubMembersOrderFieldJoinedAt ClubMembersOrderField = "JOINED_AT"
)

var AllClubMembersOrderField = []ClubMembersOrderField{
	ClubMembersOrderFieldJoinedAt,
}

func (e ClubMembersOrderField) IsValid() bool {
	switch e {
	case ClubMembersOrderFieldJoinedAt:
		return true
	}
	return false
}

func (e ClubMembersOrderField) String() string {
	return string(e)
}

func (e *ClubMembersOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClubMembersOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClubMembersOrderField", str)
	}
	return nil
}

func (e ClubMembersOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// Properties by which club connections can be ordered.
type ClubsOrderField string

const (
	// Club by created time
	ClubsOrderFieldCreatedAt ClubsOrderField = "CREATED_AT"
)

var AllClubsOrderField = []ClubsOrderField{
	ClubsOrderFieldCreatedAt,
}

func (e ClubsOrderField) IsValid() bool {
	switch e {
	case ClubsOrderFieldCreatedAt:
		return true
	}
	return false
}

func (e ClubsOrderField) String() string {
	return string(e)
}

func (e *ClubsOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClubsOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClubsOrderField", str)
	}
	return nil
}

func (e ClubsOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
