apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa
  labels:
    app: medusa
spec:
  selector:
    matchLabels:
      app: medusa
  template:
    metadata:
      labels:
        app: medusa
    spec:
      containers:
        - name: medusa
          image: medusa-image
          ports:
            - containerPort: 8080