// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gen

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"sync"

	"github.com/99designs/gqlgen/plugin/federation/fedruntime"
)

var (
	ErrUnknownType  = errors.New("unknown type")
	ErrTypeNotFound = errors.New("type not found")
)

func (ec *executionContext) __resolve__service(ctx context.Context) (fedruntime.Service, error) {
	if ec.DisableIntrospection {
		return fedruntime.Service{}, errors.New("federated introspection disabled")
	}

	var sdl []string

	for _, src := range sources {
		if src.BuiltIn {
			continue
		}
		sdl = append(sdl, src.Input)
	}

	return fedruntime.Service{
		SDL: strings.Join(sdl, "\n"),
	}, nil
}

func (ec *executionContext) __resolve_entities(ctx context.Context, representations []map[string]interface{}) []fedruntime.Entity {
	list := make([]fedruntime.Entity, len(representations))

	repsMap := map[string]struct {
		i []int
		r []map[string]interface{}
	}{}

	// We group entities by typename so that we can parallelize their resolution.
	// This is particularly helpful when there are entity groups in multi mode.
	buildRepresentationGroups := func(reps []map[string]interface{}) {
		for i, rep := range reps {
			typeName, ok := rep["__typename"].(string)
			if !ok {
				// If there is no __typename, we just skip the representation;
				// we just won't be resolving these unknown types.
				ec.Error(ctx, errors.New("__typename must be an existing string"))
				continue
			}

			_r := repsMap[typeName]
			_r.i = append(_r.i, i)
			_r.r = append(_r.r, rep)
			repsMap[typeName] = _r
		}
	}

	isMulti := func(typeName string) bool {
		switch typeName {
		default:
			return false
		}
	}

	resolveEntity := func(ctx context.Context, typeName string, rep map[string]interface{}, idx []int, i int) (err error) {
		// we need to do our own panic handling, because we may be called in a
		// goroutine, where the usual panic handling can't catch us
		defer func() {
			if r := recover(); r != nil {
				err = ec.Recover(ctx, r)
			}
		}()

		switch typeName {
		case "Account":
			resolverName, err := entityResolverNameForAccount(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "Account": %w`, err)
			}
			switch resolverName {

			case "findAccountByID":
				id0, err := ec.unmarshalNID2overdollᚋlibrariesᚋgraphqlᚋrelayᚐID(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findAccountByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindAccountByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "Account": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "AccountInfractionHistory":
			resolverName, err := entityResolverNameForAccountInfractionHistory(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "AccountInfractionHistory": %w`, err)
			}
			switch resolverName {

			case "findAccountInfractionHistoryByID":
				id0, err := ec.unmarshalNID2overdollᚋlibrariesᚋgraphqlᚋrelayᚐID(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findAccountInfractionHistoryByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindAccountInfractionHistoryByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "AccountInfractionHistory": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "Post":
			resolverName, err := entityResolverNameForPost(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "Post": %w`, err)
			}
			switch resolverName {

			case "findPostByID":
				id0, err := ec.unmarshalNID2overdollᚋlibrariesᚋgraphqlᚋrelayᚐID(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findPostByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindPostByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "Post": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "PostAuditLog":
			resolverName, err := entityResolverNameForPostAuditLog(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "PostAuditLog": %w`, err)
			}
			switch resolverName {

			case "findPostAuditLogByID":
				id0, err := ec.unmarshalNID2overdollᚋlibrariesᚋgraphqlᚋrelayᚐID(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findPostAuditLogByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindPostAuditLogByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "PostAuditLog": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "PostRejectionReason":
			resolverName, err := entityResolverNameForPostRejectionReason(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "PostRejectionReason": %w`, err)
			}
			switch resolverName {

			case "findPostRejectionReasonByID":
				id0, err := ec.unmarshalNID2overdollᚋlibrariesᚋgraphqlᚋrelayᚐID(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findPostRejectionReasonByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindPostRejectionReasonByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "PostRejectionReason": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "PostReport":
			resolverName, err := entityResolverNameForPostReport(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "PostReport": %w`, err)
			}
			switch resolverName {

			case "findPostReportByID":
				id0, err := ec.unmarshalNID2overdollᚋlibrariesᚋgraphqlᚋrelayᚐID(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findPostReportByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindPostReportByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "PostReport": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "PostReportReason":
			resolverName, err := entityResolverNameForPostReportReason(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "PostReportReason": %w`, err)
			}
			switch resolverName {

			case "findPostReportReasonByID":
				id0, err := ec.unmarshalNID2overdollᚋlibrariesᚋgraphqlᚋrelayᚐID(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findPostReportReasonByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindPostReportReasonByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "PostReportReason": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}

		}
		return fmt.Errorf("%w: %s", ErrUnknownType, typeName)
	}

	resolveManyEntities := func(ctx context.Context, typeName string, reps []map[string]interface{}, idx []int) (err error) {
		// we need to do our own panic handling, because we may be called in a
		// goroutine, where the usual panic handling can't catch us
		defer func() {
			if r := recover(); r != nil {
				err = ec.Recover(ctx, r)
			}
		}()

		switch typeName {

		default:
			return errors.New("unknown type: " + typeName)
		}
	}

	resolveEntityGroup := func(typeName string, reps []map[string]interface{}, idx []int) {
		if isMulti(typeName) {
			err := resolveManyEntities(ctx, typeName, reps, idx)
			if err != nil {
				ec.Error(ctx, err)
			}
		} else {
			// if there are multiple entities to resolve, parallelize (similar to
			// graphql.FieldSet.Dispatch)
			var e sync.WaitGroup
			e.Add(len(reps))
			for i, rep := range reps {
				i, rep := i, rep
				go func(i int, rep map[string]interface{}) {
					err := resolveEntity(ctx, typeName, rep, idx, i)
					if err != nil {
						ec.Error(ctx, err)
					}
					e.Done()
				}(i, rep)
			}
			e.Wait()
		}
	}
	buildRepresentationGroups(representations)

	switch len(repsMap) {
	case 0:
		return list
	case 1:
		for typeName, reps := range repsMap {
			resolveEntityGroup(typeName, reps.r, reps.i)
		}
		return list
	default:
		var g sync.WaitGroup
		g.Add(len(repsMap))
		for typeName, reps := range repsMap {
			go func(typeName string, reps []map[string]interface{}, idx []int) {
				resolveEntityGroup(typeName, reps, idx)
				g.Done()
			}(typeName, reps.r, reps.i)
		}
		g.Wait()
		return list
	}
}

func entityResolverNameForAccount(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m  map[string]interface{}
			ok bool
		)
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findAccountByID", nil
	}
	return "", fmt.Errorf("%w for Account", ErrTypeNotFound)
}

func entityResolverNameForAccountInfractionHistory(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m  map[string]interface{}
			ok bool
		)
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findAccountInfractionHistoryByID", nil
	}
	return "", fmt.Errorf("%w for AccountInfractionHistory", ErrTypeNotFound)
}

func entityResolverNameForPost(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m  map[string]interface{}
			ok bool
		)
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findPostByID", nil
	}
	return "", fmt.Errorf("%w for Post", ErrTypeNotFound)
}

func entityResolverNameForPostAuditLog(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m  map[string]interface{}
			ok bool
		)
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findPostAuditLogByID", nil
	}
	return "", fmt.Errorf("%w for PostAuditLog", ErrTypeNotFound)
}

func entityResolverNameForPostRejectionReason(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m  map[string]interface{}
			ok bool
		)
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findPostRejectionReasonByID", nil
	}
	return "", fmt.Errorf("%w for PostRejectionReason", ErrTypeNotFound)
}

func entityResolverNameForPostReport(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m  map[string]interface{}
			ok bool
		)
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findPostReportByID", nil
	}
	return "", fmt.Errorf("%w for PostReport", ErrTypeNotFound)
}

func entityResolverNameForPostReportReason(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m  map[string]interface{}
			ok bool
		)
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findPostReportReasonByID", nil
	}
	return "", fmt.Errorf("%w for PostReportReason", ErrTypeNotFound)
}
