build:
  targets:
    - //applications/buffer:buffer

unit_test:
  targets:
    - //applications/buffer/src/app/...
    - //applications/buffer/src/domain/...
    - //applications/buffer/src/ports/...

integration_test:
  setup:
    target: //applications/buffer:publish-testing
    dockerfile: ./applications/buffer/.ci/docker-compose.yaml
  targets:
    - //applications/buffer/src/adapters/...
    - //applications/buffer/src/service/...