services:
  eva-init:
    image: $DOCKER_REGISTRY/eva-dev:$CONTAINER_TAG
    working_dir: ../
    command: >
      ./eva_ db migrate
      && ./eva_ db seed
    env_file:
      - .env.ci
    depends_on:
      - elasticsearch
      - scylla

  eva-http:
    image: $DOCKER_REGISTRY/eva-dev:$CONTAINER_TAG
    working_dir: ../
    command: ./eva_ http
    ports:
      - "127.0.0.1:3020:$PORT"
    env_file:
      - .env.ci
    depends_on:
      - eva-init

  eva-grpc:
    image: $DOCKER_REGISTRY/eva-dev:$CONTAINER_TAG
    working_dir: ../
    command: ./eva_ grpc
    ports:
      - "127.0.0.1:3030:$PORT"
    env_file:
      - .env.ci
    depends_on:
      - eva-init