version: '3.9'
services:
  loader-worker:
    image: $CONTAINER_REGISTRY/loader/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/loader/internal/image.binary db migrate keyspace &&  /app/applications/loader/internal/image.binary worker"
    env_file: ../../applications/loader/.env.ci
    depends_on:
      - temporal
      - elasticsearch
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20
    networks:
      web:

  run:
    depends_on:
      - loader-worker
