version: '3.9'
services:
  loader:
    image: $CONTAINER_REGISTRY/loader/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/loader/internal/image.binary db migrate keyspace && /app/applications/loader/internal/image.binary"
    env_file: ../../applications/loader/.env.ci
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.buffer.rule=Path(`/api/upload/{document}`) || Path(`/api/upload/`)"
      - "traefik.http.routers.buffer.entrypoints=websecure"
      - "traefik.http.routers.buffer.tls=true"
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - traefik
      - temporal
      - elasticsearch
    ports:
      - 3340:8000
      - 3350:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - loader
