steps:
  build:
    targets:
      - //applications/loader/internal:image

  unit_test:
    coverage:
      - name: loader.unit
        paths:
          - ./applications/loader/**/coverage.dat
    targets:
      - //applications/loader/internal/app/...
      - //applications/loader/internal/domain/...
      - //applications/loader/internal/ports/...

  integration_test:
    pre_hook:
      - //applications/loader/internal:internal -- db migrate keyspace
      - //applications/loader/internal:internal -- db seed
    coverage:
      - name: loader.integration
        paths:
          - ./applications/loader/internal/adapters/**/coverage.dat
      - name: loader.component
        paths:
          - ./applications/loader/internal/service/**/coverage.dat
    targets:
      - //applications/loader/internal/adapters/...
      - //applications/loader/internal/service/...

  push_image:
    targets:
      - //applications/loader/internal:publish

  e2e_test:
    setup:
      dockerfile:
        - ./applications/loader/docker-compose.ci.e2e.yaml
    network_dependencies:
      - host: loader
        port: 8000
        priority: 0

  publish_image:
    copy:
      - from_repo: loader/dev
        to_repo: loader
