version: '3.9'
services:
  hades:
    image: $CONTAINER_REGISTRY/hades/dev:$BUILDKITE_COMMIT
    entrypoint: ""
    command: /bin/sh -c "/app/applications/hades/internal/image.binary db migrate keyspace && /app/applications/hades/internal/image.binary db seed && /app/applications/hades/internal/image.binary index all && /app/applications/hades/internal/image.binary"
    env_file: ../../applications/hades/.env.ci
    depends_on:
      - temporal
    ports:
      - 7532:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hades.rule=PathPrefix(`/api/ccbill/*`)"
      - "traefik.http.routers.hades.entrypoints=websecure"
      - "traefik.http.routers.hades.tls=true"
      - "traefik.port=8000"
    environment:
      - CCBILL_FLEXFORMS_URL=${CCBILL_FLEXFORMS_URL}
      - CCBILL_SALT_KEY=${CCBILL_SALT_KEY}
      - CCBILL_ACCOUNT_NUMBER=${CCBILL_ACCOUNT_NUMBER}
      - CCBILL_SUB_ACCOUNT_NUMBER=${CCBILL_SUB_ACCOUNT_NUMBER}
      - CCBILL_DATALINK_USERNAME=${CCBILL_DATALINK_USERNAME}
      - CCBILL_DATALINK_PASSWORD=${CCBILL_DATALINK_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

  run:
    depends_on:
      - hades
