version: '3.5'
services:
  redis:
    image: "redis:alpine"
    networks:
      - network

  temporal:
    container_name: temporal
    restart: unless-stopped
    depends_on:
      - scylla
    environment:
      - CASSANDRA_SEEDS=cassandra
      - DYNAMIC_CONFIG_FILE_PATH=config/temporal.yaml
    image: temporalio/auto-setup:1.9.2
    networks:
      - network
    ports:
      - 7233:7233
    volumes:
      - ./services/temporal.yaml:/etc/temporal/config/temporal.yaml

  scylla:
    image: "scylladb/scylla:4.3.1"
    container_name: scylla
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ./target:/var/lib/scylla
    ports:
      - "127.0.0.1:9042:9042"
      - "127.0.0.1:9160:9160"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped
    networks:
      - network

networks:
  net:
    driver: bridge
    name: network