version: '3.9'
services:
  traefik:
    image: traefik:v2.1
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - 8000:80
      - 4343:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  temporal:
    depends_on:
      - scylla
    environment:
      - DB=cassandra
      - CASSANDRA_SEEDS=scylla
      - CASSANDRA_HOST=scylla
      - DYNAMIC_CONFIG_FILE_PATH=config/temporal.yaml
    image: temporalio/auto-setup:1.9.2
    ports:
      - 7233:7233
    volumes:
      - ./services/temporal.yaml:/etc/temporal/config/temporal.yaml

  scylla:
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla-data:/var/lib/scylla
    ports:
      - 9042:9042
      - 9160:9160
    networks:
      scylla-web:

  scylla-node2:
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla-data:/var/lib/scylla
    networks:
      scylla-web:

  scylla-node3:
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla-data:/var/lib/scylla
    networks:
      scylla-web:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  redis:
    image: "redis:5.0-alpine3.13"
    ports:
      - 6379:6379

volumes:
  elasticsearch-data:
    driver: local
  scylla-data:
    driver: local

networks:
  scylla-web:
    driver: bridge
