version: '3.9'
services:
  redis:
    image: "redis:alpine"

  temporal:
    restart: unless-stopped
    depends_on:
      - scylla
    environment:
      - DB=cassandra
      - CASSANDRA_SEEDS=scylla
      - CASSANDRA_HOST=scylla
      - DYNAMIC_CONFIG_FILE_PATH=config/temporal.yaml
    image: temporalio/auto-setup:1.9.2
    ports:
      - 7233:7233
    volumes:
      - ./services/temporal.yaml:/etc/temporal/config/temporal.yaml

  scylla:
    image: "scylladb/scylla:4.3.1"
    restart: unless-stopped
    command:
      - "--smp"
      - "1"
    volumes:
      - scylla-data:/var/lib/scylla
    ports:
      - 9042:9042
      - 9160:9160

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped

volumes:
  elasticsearch-data:
    driver: local
  scylla-data:
    driver: local