version: '2.2'
services:
  traefik:
    image: traefik:v2.1
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - 8310:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  temporal:
    depends_on:
      - scylla
    environment:
      - DB=cassandra
      - CASSANDRA_SEEDS=scylla
      - CASSANDRA_HOST=scylla
      - DYNAMIC_CONFIG_FILE_PATH=config/temporal.yaml
    image: temporalio/auto-setup:1.14.1
    ports:
      - 7233:7233
    volumes:
      - ./services/temporal.yaml:/etc/temporal/config/temporal.yaml
