# common env variables
steps:
  integration_test:
    setup:
      env:
        AWS_ACCESS_KEY_LOADER: overdoll123
        AWS_ACCESS_SECRET_LOADER: overdoll123
        AWS_ENDPOINT_LOADER: http://minio:9000
        AWS_REGION_LOADER: us-east-1
        DB_HOST: scylla
        ELASTICSEARCH_URL: http://elasticsearch:9200
        TEMPORAL_URL: temporal:7233
        TEMPORAL_NAMESPACE: default
        GIN_MODE: debug
        APP_DEBUG: "true"
        EVA_SERVICE: eva:8080
        PARLEY_SERVICE: parley:8080
        STING_SERVICE: sting:8080
        CARRIER_SERVICE: carrier:8080
        LOADER_SERVICE: loader:8080
        STELLA_SERVICE: stella:8080
        APP_KEY: AES256Key-32Characters1234567890
        SESSION_SECRET: AES256Key-32Characters1234567890
        REDIS_HOST: redis
        STATIC_URL: https://traefik
        APP_URL: https://traefik
        LIBWEBP_VERSION: 1.1.0
        COOKIE_KEY: AES256Key-32Characters1234567890
        COOKIE_BLOCK_KEY: AES256Key-32Characters1234567890
        PASSPORT_SECRET: passport_secret
        GEOIP_DATABASE_LOCATION: internal/service/file_fixtures/GeoIP2-City-Test.mmdb
        EMAIL_FROM_NAME: overdoll
        EMAIL_FROM_ADDRESS: please-dont-reply@overdoll.com
        EMAIL_DOMAIN_WHITELIST: inbox.testmail.app
