version: '3.5'
services:
  buffer:
    image: $CONTAINER_REGISTRY/buffer/dev:$BUILDKITE_COMMIT
    command: ./buffer_ http
    ports:
      - 3010:8000
    env_file:
      - .env.ci

  run:
    depends_on:
      - buffer