steps:
  build:
    targets:
      - //applications/buffer:buffer
    push:
      - //applications/buffer:publish-testing

  unit_test:
    targets:
      - //applications/buffer/src/app/...
      - //applications/buffer/src/domain/...
      - //applications/buffer/src/ports/...

  integration_test:
    setup:
      dockerfile:
        - ./applications/buffer/docker-compose.ci.yaml
    targets:
      - //applications/buffer/src/adapters/...
      - //applications/buffer/src/service/...

  e2e_test:
    setup:
      dockerfile:
        - ./applications/buffer/docker-compose.ci.yaml