steps:
  build:
    targets:
      - //applications/buffer/internal:internal

  unit_test:
    coverage:
      - name: buffer.unit
        paths:
          - ./applications/buffer/**/coverage.dat
    targets:
      - //applications/buffer/internal/app/...
      - //applications/buffer/internal/domain/...
      - //applications/buffer/internal/ports/...

  push_image:
    targets:
      - //applications/buffer/internal:publish-testing

  integration_test:
    coverage:
      - name: buffer.integration
        paths:
          - ./applications/buffer/internal/adapters/**/coverage.dat
    targets:
      - //applications/buffer/internal/adapters/...

  e2e_test:
    setup:
      dockerfile:
        - ./applications/buffer/docker-compose.e2e.yaml

  publish_image:
    targets:
      - //applications/buffer/internal:publish