kind: ConfigMap
metadata:
  name: scylla-config
  namespace: scylla
apiVersion: v1
data:
  scylla.yaml: |-

    api_address: 127.0.0.1
    api_doc_dir: /opt/scylladb/api/api-doc/
    api_port: 10000
    api_ui_dir: /opt/scylladb/swagger-ui/dist/
    batch_size_fail_threshold_in_kb: 50
    batch_size_warn_threshold_in_kb: 5
    cas_contention_timeout_in_ms: 1000
    cluster_name: simple-cluster
    commitlog_segment_size_in_mb: 32
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    commitlog_total_space_in_mb: -1
    endpoint_snitch: GossipingPropertyFileSnitch
    listen_address: 127.0.0.1
    murmur3_partitioner_ignore_msb_bits: 12
    native_transport_port: 9042
    num_tokens: 256
    partitioner: org.apache.cassandra.dht.Murmur3Partitioner
    read_request_timeout_in_ms: 5000
    rpc_address: 127.0.0.1
    start_rpc: true
    rpc_port: 9160
    seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
      - seeds: 127.0.0.1
        write_request_timeout_in_ms: 2000