// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AccountData struct {
	Registered  bool `json:"registered"`
	SameSession bool `json:"sameSession"`
}

type Authentication struct {
	Success bool `json:"success"`
}

type AuthenticationState struct {
	Authorized bool `json:"authorized"`
	Registered bool `json:"registered"`
	Redirect   bool `json:"redirect"`
}

type JoinState struct {
	ExistingUser bool `json:"existingUser"`
}

type Registration struct {
	Username string `json:"username"`
}

type SameSession struct {
	Same bool `json:"same"`
}
