// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AuthListener struct {
	SameSession bool    `json:"sameSession"`
	Cookie      *Cookie `json:"cookie"`
}

type Authentication struct {
	Cookie *Cookie `json:"cookie"`
	User   *User   `json:"user"`
}

type AuthenticationInput struct {
	Email string `json:"email"`
}

type Cookie struct {
	SameSession bool   `json:"sameSession"`
	Registered  bool   `json:"registered"`
	Redeemed    bool   `json:"redeemed"`
	Session     string `json:"session"`
	Email       string `json:"email"`
}

type PostInput struct {
	Images            []string `json:"images"`
	Categories        []string `json:"categories"`
	Characters        []string `json:"characters"`
	CategoryRequests  []string `json:"categoryRequests"`
	MediaRequests     []string `json:"mediaRequests"`
	CharacterRequests []string `json:"characterRequests"`
	ArtistID          *string  `json:"artistId"`
	ArtistUsername    string   `json:"artistUsername"`
}

type PostResponse struct {
	Review bool `json:"review"`
}

type RegisterInput struct {
	Username string `json:"username"`
}

type User struct {
	Username string `json:"username"`
}
