export { default as CreditCardVisa } from './credit-cards/visa.svg'
export { default as CreditCardMasterCard } from './credit-cards/mastercard.svg'
export { default as CreditCardJCB } from './credit-cards/jcb.svg'
export { default as CreditCardDiscover } from './credit-cards/discover.svg'
export { default as CreditCardAmex } from './credit-cards/amex.svg'
